#![allow(missing_docs)]

//! Errors generated by isolate.
error_chain!{
    // Wrappers for other error_chains.
    links {
    }

    // Wrappers for other errors.
    foreign_links {
        Io(::std::io::Error);
        Nul(::std::ffi::NulError);
        Utf8(::std::str::Utf8Error);
        Nix(::nix::Error);
    }

    // Internally defined errors.
    errors {
        StackAllocation {
            description("Could not map stack region.")
        }
    }
}
