//! Errors generated by isolate.
error_chain!{
    // Wrappers for other error_chains.
    links {
    }

    // Wrappers for other errors.
    foreign_links {
    }

    // Internally defined errors.
    errors {
    }
}
